### PR TITLE
LSTMCell converter

### LINKED ISSUE #108: Add support for aten::lstm_cell
## aten::lstm_cell

- **Function Schema**: lstm_cell(Tensor input, Tensor[] hx, Tensor w_ih, Tensor w_hh, Tensor? b_ih=None, Tensor? b_hh=None) -> (Tensor, Tensor)

- **Original PyTorch API**: https://pytorch.org/docs/master/generated/torch.nn.LSTMCell.html

- **Relevant TensorRT Documentation**:

### PR DESCRIPTION
**Pull request by abhi-iyer**
# Description

LSTMCell converter

function schema: `lstm_cell(Tensor input, Tensor[] hx, Tensor w_ih, Tensor w_hh, Tensor? b_ih=None, Tensor? b_hh=None) -> (Tensor, Tensor)`

Fixes #108 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation and have regenerated the documentation (`make html` in docsrc)
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abhi-iyer** [comment]
A potential snippet to test with:

```

**Comment by narendasan** [comment]
Any luck on the varying difference issue?

**Comment by narendasan** [comment]
TensorRT does not guarantee binding order so we will need to develop a convention for multiple outputs and inputs

**Comment by narendasan** [comment]
Binding order issue should now be addressed

**Pull request merged**
