### PR TITLE
add ELU converter to core library

### PR DESCRIPTION
**Pull request by bowang95**
# Description

Add ELU converter to our core library.

## Type of change

Please delete options that are not relevant and/or add your own.

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by peri044 — CHANGES_REQUESTED** [review]
Add patch file or instructions to let users know that this converter code needs to be disabled for [https://github.com/NVIDIA/TRTorch/pull/349](url) to work.

**Comment by bowang95** [comment]
> Add patch file or instructions to let users know that this converter code needs to be disabled for [https://github.com/NVIDIA/TRTorch/pull/349](url) to work.

Yes, my thought is that we keep this core part, while we create a patch file under elu converter example directory.

**Comment by peri044** [comment]
> > Add patch file or instructions to let users know that this converter code needs to be disabled for [https://github.com/NVIDIA/TRTorch/pull/349](url) to work.
> 
> Yes, my thought is that we keep this in our core library, while we create a patch file under elu converter example directory. So, elu converter is included in our core library in default, and users can run patch file to discard this commit change if they want to test the self compiling .so feature. So, I will put patch file in that PR, is this ok?

Oh okay. You want to have another PR for the patch file. Sounds good.

**Review by narendasan — APPROVED** [review]
lgtm

**Comment by narendasan** [comment]
@peri044 is this good to go from your side?

**Comment by peri044** [comment]
yeah. LGTM

**Pull request merged**
