### PR TITLE
chore: Add efficientnet b0 and VIT to testsuite

### PR DESCRIPTION
**Pull request by peri044**
# Description

Add efficientnet and vit to testsuite

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by narendasan — COMMENTED** [review]
Can we change these tests slightly so that the threshold is an argument? would be good not to lower the threshold for the existing networks

**Comment by peri044** [comment]
@narendasan The threshold needs to be increased for VIT. I think it might be because of GeLU. The difference for a test image that I saw is around (6~7)e-3. Accuracy on imagenet seems to be almost similar to pytorch.

**Comment by narendasan** [comment]
Yeah so we should parameterize the threshold like we do the model and the input size so that only VIT uses the lower threshold

**Comment by peri044** [comment]
> Yeah so we should parameterize the threshold like we do the model and the input size so that only VIT uses the lower threshold

Done.

**Review by narendasan — APPROVED** [review]
lgtm

**Pull request merged**
