### PR TITLE
Torch 1.6.0 update

### LINKED ISSUE #1: Module tests fail because of segfault in cuDNN destructor
The tests pass functionality wise, but in the clean up, the test segfaults. It seems like this is a issue others have seen in libtorch https://github.com/pytorch/pytorch/issues/17658

### PR DESCRIPTION
**Pull request by narendasan**
# Description

Updates the compiler for PyTorch 1.6.0. Breaking change: drops support for Python 3.5. Known issue: Bug with PyTorch some int[] are not parsable with the IR parsing tools. Issue has been raised with PyTorch team. Shuffle case fails due to this issue. Solve issues with segfaults during cuDNN clean up. 

Fixes #1  

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas and hacks
- [X] I have made corresponding changes to the documentation and have regenerated the documentation (`make html` in docsrc)
- [X] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by xsacha** [comment]
Just tried to build it (Windows) and got:

> ERROR: C:/work/trtorch/cpp/api/lib/BUILD:3:10: Linking of rule '//cpp/api/lib:libtrtorch.so' failed (Exit 1120)
> LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
> LINK : warning LNK4044: unrecognized option '/Wl,-rpath,lib/'; ignored
>    Creating library bazel-out/x64_windows-opt/bin/cpp/api/lib/libtrtorch.so.if.lib and object bazel-out/x64_windows-opt/bin/cpp/api/lib/libtrtorch.so.if.exp
> plugins.lo.lib(interpolate_plugin.obj) : error LNK2019: unresolved external symbol getPluginRegistry referenced in function "public: __cdecl nvinfer1::PluginRegistrar<class trtorch::core::conversion::converters::impl::plugins::InterpolatePluginCreator>::PluginRegistrar<class trtorch::core::conversion::converters::impl::plugins::InterpolatePluginCreator>(void)" (??0?$PluginRegistrar@VInterpolatePluginCreator@plugins@impl@converters@conversion@core@trtorch@@@nvinfer1@@QEAA@XZ)
> execution.lo.lib(TRTEngine.obj) : error LNK2019: unresolved external symbol createInferRuntime_INTERNAL referenced in function "public: __cdecl trtorch::core::execution::TRTEngine::TRTEngine(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0TRTEngine@execution@core@trtorch@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)
> conversionctx.lib(ConversionCtx.obj) : error LNK2019: unresolved external symbol createInferBuilder_INTERNAL referenced in function "public: __cdecl trtorch::core::conversion::ConversionCtx::ConversionCtx(struct trtorch::core::conversion::BuilderSettings)" (??0ConversionCtx@conversion@core@trtorch@@QEAA@UBuilderSettings@123@@Z)
> bazel-out\x64_windows-opt\bin\cpp\api\lib\libtrtorch.so : fatal error LNK1120: 3 unresolved externals
> Target //:libtrtorch failed to build

**Comment by narendasan** [comment]
These look like linker for missing symbols from libnvinfer. Ill have to take a look at the Windows build in a bit. I am still making some changes for Linux.

**Comment by xsacha** [comment]
Oh yeah, I've added it back to compile it, but the other issues below remain. It's the issue in https://github.com/NVIDIA/TRTorch/issues/153 so probably Windows only.

**Comment by narendasan** [comment]
Hmm, seems like that error is actually caused by some issue earlier in the compilation process. I see 
```
DEBUG: [TRTorch - Debug Build] - Input shape is less than 4D got: [], inserting shuffle layer to reshape to 4D tensor shape: [1, 1, 1, 1]
```
Which is odd for the input to prelu. That would explain why you cannot broadcast here

**Comment by xsacha** [comment]
The issues I'm facing do not seem to be related to this PR in any case.

**Pull request merged**
