### PR TITLE
fix: Fix linear lowering pass, lift layer_norm scale layer restriction and matmul layer nbdims restriction

### PR DESCRIPTION
**Pull request by peri044**
# Description
These are the changes required for vision transformer network to work. 

Layer norm : Scale layer has a restriction where it requires the dims to greater than 3.
Matmul: Previously both the tensors were required to have same number of dimensions. Lifted this restriction.
Linear lowering pass : Subgraph writer is not working as expected for "None " bias. It matches even the valid Bias tensor case. Replaced this with new functionality which checks the types of tensors.

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by narendasan — COMMENTED** [review]
Can we add tests for this?

**Comment by peri044** [comment]
> Can we add tests for this?

Added testcases for all of them.

**Comment by peri044** [comment]
@narendasan Added efficientnet from timm library to the test suite. I'll list all the models somewhere in a README in a separate PR.

**Review by narendasan — APPROVED** [review]
LGTM

**Pull request merged**
