### PR TITLE
support adaptive_max_pooling, fix adpative_avg_pooling bug

### PR DESCRIPTION
**Pull request by inocsin**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
- Bug fix (non-breaking change which fixes an issue)
Fix aten::adaptive_avg_pool2d bug when input size is not integer multiple of output size, update the test case
- New feature (non-breaking change which adds functionality)
Support aten::adaptive_max_pool2d with test case
-Bug fix
Remove "#if NV_TENSORRT_MAJOR < 7 || (NV_TENSORRT_MAJOR == 7 && NV_TENSORRT_MINOR < 1)" part.
Since the TensorRT dependency is updated, the original GPU part will never be used, all the operator will be forced to run on cpu. So I remove the TensorRT flag. But the GPU part failed with unknow reason after the flag was removed, so I refactored the gpu part, now it can run on GPU correctly.

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by narendasan** [comment]
Can you apply the linting?

**Comment by inocsin** [comment]
> Can you apply the linting?

applied linting

**Comment by peri044** [comment]
The tests are running fine. It looks like the existing Interpolate plugin already calls `at::adaptive_avg_pool2d`  by using the mode `adaptive_pool2d` [https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/plugins/interpolate_plugin.cpp#L329](url)
Can we make use of the mode flag to  support adaptive_max_pool2d as well ? Does this require a separate plugin in this PR?

**Comment by inocsin** [comment]
> The tests are running fine. It looks like the existing Interpolate plugin already calls `at::adaptive_avg_pool2d` by using the mode `adaptive_pool2d` [https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/plugins/interpolate_plugin.cpp#L329](url)
> Can we make use of the mode flag to support adaptive_max_pool2d as well ? Does this require a separate plugin in this PR?

The output number, datatype and parameter number of adaptive_max_pool are different from interpolate_plugin, in that case should we use several if-else to merge these two plugin into one?

**Comment by inocsin** [comment]
@narendasan @peri044 please review the update, I have fixed some bugs

**Comment by peri044** [comment]
Thanks @inocsin Merged these changes into the new plugins interface. Tried to cherry pick your commits but there are lot of changes in the new API.

**Pull request closed without merging**
